// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:cbb675a9-885e-44f1-baa5-4cb0243db6a0",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_tFhRE5TRe",
    "aws_user_pools_web_client_id": "1qqt8uh146epjiotlqs27l6ml1",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "events",
            "region": "us-west-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "eventscrud",
            "endpoint": "https://s3pxbz9b92.execute-api.us-west-2.amazonaws.com/Prod",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
