// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:59782cca-8573-4ca1-b9e9-d5fbe78a12d3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_iMyCgPOVN",
    "aws_user_pools_web_client_id": "mgig3q3o7dfq2l7r9t58cc5cf"
};


export default awsmobile;
