# NOTE: update this with your service name
service: fsa-sls

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"



functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  createResource:
    handler: createResource.main
    events:
      - http:
          path: resources
          method: post
          cors: true
          authorizer: aws_iam

  getResource:
    handler: getResource.main
    events:
      - http:
          path: resources/{id}
          method: get
          cors: true
          authorizer: aws_iam

  listResource:
    handler: listResource.main
    events:
      - http:
          path: resources
          method: get
          cors: true
          authorizer: aws_iam

  updateResource:
    handler: updateResource.main
    events:
      - http: 
          path: resources/{id}
          method: put
          cors: true
          authorizer: aws_iam

  deleteResource:
    handler: deleteResource.main
    events:
      - http:
          path: reources/{id}
          method: delete
          cors: true
          authorizer: aws_iam