// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:fb05daf1-d476-470a-94dc-c50ed8037058",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_I5erhPU7P",
    "aws_user_pools_web_client_id": "6nu520p25sbt8t7bqkjsgcif02"
};


export default awsmobile;
